from enum import StrEnum

from pydantic import Field

from .base import CanonicalModel, PaiseField


class BreakClass(StrEnum):
    CLEAN_MATCH = "CLEAN_MATCH"
    ROUNDING_VARIANCE = "ROUNDING_VARIANCE"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    FEE_VARIANCE = "FEE_VARIANCE"
    TAX_VARIANCE = "TAX_VARIANCE"
    SETTLEMENT_CUTOFF = "SETTLEMENT_CUTOFF"
    DELAYED_SETTLEMENT = "DELAYED_SETTLEMENT"
    INSTANT_SETTLEMENT_VARIANCE = "INSTANT_SETTLEMENT_VARIANCE"
    REFUND_NETTED_LATER = "REFUND_NETTED_LATER"
    PARTIAL_REFUND = "PARTIAL_REFUND"
    MANGLED_UTR = "MANGLED_UTR"
    MANGLED_NARRATION = "MANGLED_NARRATION"
    DUPLICATE_LEDGER_ROW = "DUPLICATE_LEDGER_ROW"
    DUPLICATE_BANK_CREDIT = "DUPLICATE_BANK_CREDIT"
    DISPUTE_ADJUSTMENT = "DISPUTE_ADJUSTMENT"
    GENERAL_ADJUSTMENT = "GENERAL_ADJUSTMENT"
    MISSING_ORDER = "MISSING_ORDER"
    MISSING_PAYMENT = "MISSING_PAYMENT"
    MISSING_SETTLEMENT = "MISSING_SETTLEMENT"
    MISSING_BANK_CREDIT = "MISSING_BANK_CREDIT"
    UNRESOLVABLE = "UNRESOLVABLE"


class ResolutionStatus(StrEnum):
    AUTO_RESOLVED = "AUTO_RESOLVED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    ESCALATED = "ESCALATED"
    REJECTED = "REJECTED"


class ReconciliationException(CanonicalModel):
    exception_id: str
    break_class: BreakClass
    resolution_status: ResolutionStatus
    financial_impact_paise: PaiseField
    evidence: list[str] = Field(default_factory=list)
